# Generated by Django 2.2.3 on 2019-07-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
