# Generated by Django 2.2.3 on 2019-07-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='areas',
            field=models.ManyToManyField(related_name='professors', to='training.Area', verbose_name='Areas de preferencia'),
        ),
    ]
