# Generated by Django 2.2.3 on 2019-07-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190704_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('DC', 'Director'), ('D', 'Docente')], max_length=2, verbose_name='Tipo de Usuario'),
        ),
    ]
