# Generated by Django 2.2.3 on 2019-07-04 18:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualiación')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre capacitación')),
                ('accredited_hours', models.IntegerField(default=1, verbose_name='Horas acreditadas')),
                ('place', models.CharField(max_length=50, verbose_name='Lugar')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha inicio')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha finalización')),
                ('state', models.CharField(choices=[('inscriptions', 'Inscripciones'), ('emission', 'Emisión'), ('finished', 'Finalizado')], default='inscriptions', max_length=10, verbose_name='Estado capacitación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualiación')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre especialidad')),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Titulos',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha inicio')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualiación')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_center', models.CharField(max_length=100, verbose_name='Unidad educativa')),
                ('number', models.CharField(max_length=20, verbose_name='Número de registro')),
                ('level_type', models.CharField(choices=[('third', 'Tercer Nivel'), ('fourth', 'Cuarto Nivel')], max_length=100, verbose_name='Nivel')),
                ('degree_type', models.CharField(choices=[('na', 'Nacional'), ('in', 'Internacional')], max_length=100, verbose_name='Tipo de título')),
                ('emission_date', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualiación')),
                ('degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='training.Degree', verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inscripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualiación')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Course', verbose_name='Capacitación')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
    ]
