# Generated by Django 2.2.3 on 2019-07-03 02:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualiación')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha inicio')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualiación')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Número de registro')),
                ('degree', models.CharField(choices=[('third', 'Tercer Nivel'), ('fourth', 'Cuarto Nivel')], max_length=10, verbose_name='Título')),
                ('type', models.CharField(max_length=100, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualiación')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre capacitación')),
                ('accredited_hours', models.IntegerField(default=1, verbose_name='Horas acreditadas')),
                ('place', models.CharField(max_length=50, verbose_name='Lugar')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha inicio')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualiación')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='training.Area', verbose_name='Área')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Period', verbose_name='Periodo')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='training.Specialty', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
            },
        ),
    ]
