# Generated by Django 2.2.3 on 2019-07-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Professor', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='course',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='training.Area', verbose_name='Área capacitación'),
        ),
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Period', verbose_name='Periodo'),
        ),
    ]
