# Generated by Django 2.2.3 on 2019-07-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20190704_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.CharField(choices=[('inscriptions', 'Inscripciones'), ('emission', 'Emisión'), ('finished', 'Finalizado')], default='inscriptions', max_length=15, verbose_name='Estado capacitación'),
        ),
    ]
