# Generated by Django 2.2.3 on 2019-07-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_course_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='emission_date',
            field=models.DateField(null=True, verbose_name='Fecha de emisión'),
        ),
    ]
