# Generated by Django 2.2.3 on 2019-07-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_specialty_emission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='emission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de emisión'),
        ),
    ]
