# Generated by Django 2.2.3 on 2019-07-04 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20190703_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre especialidad')),
            ],
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='name',
        ),
        migrations.AddField(
            model_name='specialty',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='training.Degree', verbose_name='Nombre especialidad'),
        ),
    ]
